export const CardsObject = [
  {
    type: "home",
    buttonText: "Acessar",
    title: "Produtos",
    image: "/pedidos.jpg",
    paragraf: <>Gerenciar produtos baseado nas suas categorias.</>,
    buttonLink: "/admin/dashboard/product",
    methodRefresh: true,
  },
  {
    type: "home",
    buttonText: "Acessar",
    title: "Pedidos",
    image: "/pedidos.jpg",
    paragraf: <>Gerenciar pedidos e seus respectivos clientes.</>,
    buttonLink: "/admin/dashboard/order",
    methodRefresh: true,
  },
  {
    type: "home",
    buttonText: "Acessar",
    title: "Dashbot",
    image: "/pedidos.jpg",
    paragraf: <>Gerenciar todos os dashbots.</>,
    buttonLink: "/admin/dashboard/dashbots",
    methodRefresh: true,
  },
  {
    type: "home",
    buttonText: "Acessar",
    title: "Nenbot",
    image: "/pedidos.jpg",
    paragraf: <>Gerenciar todos os nenbots.</>,
    buttonLink: "/admin/dashboard/nenbots",
    methodRefresh: true,
  },
  {
    type: "home",
    buttonText: "Acessar",
    title: "Avisos",
    image: "/pedidos.jpg",
    paragraf: <>Gerenciar os avisos da newsletter da navbar.</>,
    buttonLink: "/admin/dashboard/newsletter",
    methodRefresh: true,
  },
];
